# Adding a new job.
#api_job_new:
#  path: /run
#  controller: App\Controller\JobController::newJob
#  methods: POST

api_job_default_results:
  path: /{id}/results
  controller: App\Controller\JobController::getJobResults
  methods: GET