#
#api_job_run:
#  path: /run
#  controller: App\Controller\JobController::runJob
#  methods: POST
#
#api_job_default_results:
#  path: /{id}/results
#  controller: App\Controller\JobController::getJobResults
#  methods: GET
#
